export const resources = [
    {
        name: "stone",
        stockpile: 0,
        visible: true,
        color: "gray",
    },
    {
        name: "wood",
        stockpile: 0,
        visible: true,
        color: "brown",
    },
    {
        name: "food",
        stockpile: 0,
        visible: true,
        color: "#4ad970",
    },
    {
        name: "seeds",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "chocolate",
    },
    {
        name: "berries",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "#d94a9d",
    },
    {
        name: "fruits",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "#e6bb10",
    },
    {
        name: "nuts",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "#916504",
    },
    {
        name: "ink",
        base: ["food",],
        stockpile: 0,
        visible: false,
        color: "#63359c",
    },
    {
        name: "gems",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "white",
    },
    {
        name: "metal",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "silver",
    },
    {
        name: "rations",
        base: ["food",],
        stockpile: 0,
        visible: false,
        color: "#31948f",
    },
    {
        name: "gourmet rations",
        base: ["food","nuts","seeds","berries","fruits"],
        stockpile: 0,
        visible: false,
        color: "#2a6696",
    },
    {
        name: "sand",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "tan",
    },
    {
        name: "glass",
        base: ["sand",],
        stockpile: 0,
        visible: false,
        color: "lightblue",
    },
    {
        name: "paper",
        base: ["wood",],
        stockpile: 0,
        visible: false,
        color: "#ebe2d5",
    },
    {
        name: "maps",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "#14592a",
    },
    {
        name: "books",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "#0b3763",
    },
    {
        name: "drawings",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "#c9792e",
    },
    {
        name: "oregami",
        base: ["paper",],
        stockpile: 0,
        visible: false,
        color: "#afc9c8",
    },
    {
        name: "jewlery",
        base: ["metal", "gems"],
        stockpile: 0,
        visible: false,
        color: "gold",
    },
    {
        name: "egg rocks",
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "divinity",
        base: ["jewlery", "fruits", "nuts", "berries", "drawings", "oregami",],
        stockpile: 0,
        visible: false,
        color: "#edc042",
    },
    {
        name: "eggs",
        base: ["egg rocks"],
        stockpile: 0,
        visible: false,
        color: "#cc36eb",
    },
]
