export const resources = [
    {
        name: "stone",
        stockpile: 0,
        visible: true,
        gain: 0,
        color: "gray",
    },
    {
        name: "wood",
        stockpile: 0,
        visible: true,
        gain: 0,
        color: "brown",
    },
    {
        name: "food",
        stockpile: 0,
        visible: true,
        gain: 0,
        color: "green",
    },
    {
        name: "seeds",
        stockpile: 0,
        visible: false,
        gain: 0,
        color: "chocolate",
    },
    {
        name: "gems",
        stockpile: 0,
        visible: false,
        gain: 0,
        color: "white",
    },
    {
        name: "metal",
        base: "stone",
        stockpile: 0,
        visible: false,
        gain: 0,
        color: "silver",
    },
    {
        name: "rations",
        base: "food",
        stockpile: 0,
        visible: false,
        gain: 0,
        color: "orange",
    },
]
