export const resources = [
    {
        name: "stone",
        stockpile: 0,
        visible: true,
        color: "gray",
    },
    {
        name: "wood",
        stockpile: 0,
        visible: true,
        color: "brown",
    },
    {
        name: "food",
        stockpile: 0,
        visible: true,
        color: "green",
    },
    {
        name: "seeds",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "chocolate",
    },
    {
        name: "berries",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "red",
    },
    {
        name: "fruits",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "red",
    },
    {
        name: "nuts",
        base: ["food"],
        stockpile: 0,
        visible: false,
        color: "red",
    },
    {
        name: "ink",
        base: ["food",],
        stockpile: 0,
        visible: false,
        color: "chocolate",
    },
    {
        name: "gems",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "white",
    },
    {
        name: "metal",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "silver",
    },
    {
        name: "rations",
        base: ["food",],
        stockpile: 0,
        visible: false,
        color: "orange",
    },
    {
        name: "gourmet rations",
        base: ["food","nuts","seeds","berries","fruits"],
        stockpile: 0,
        visible: false,
        color: "orange",
    },
    {
        name: "sand",
        base: ["stone",],
        stockpile: 0,
        visible: false,
        color: "tan",
    },
    {
        name: "glass",
        base: ["sand",],
        stockpile: 0,
        visible: false,
        color: "lightblue",
    },
    {
        name: "paper",
        base: ["wood",],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "maps",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "books",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "drawings",
        base: ["paper", "ink"],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "oregami",
        base: ["paper",],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "jewlery",
        base: ["metal", "gems"],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "egg rocks",
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "divinity",
        base: ["jewlery", "fruits", "nuts", "berries", "drawings", "oregami",],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
    {
        name: "eggs",
        base: ["egg rocks"],
        stockpile: 0,
        visible: false,
        color: "grey",
    },
]
